ECommerce.UI/Components/BrandViewComponent.cs
using ECommerce.Infrastructure.Services.Abstracts;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.UI.Components
{
    public class BrandViewComponent : ViewComponent
    {
        private readonly IBrandService _brandService;
        
        public BrandViewComponent(IBrandService brandService)
        {
            _brandService = brandService;
        }

        public IViewComponentResult Invoke()
        {
            var brands = _brandService.GetAll();
            return View(brands);
        }
    }
}

ECommerce.UI/Components/CategoryViewComponent.cs
using ECommerce.Infrastructure.Services.Abstracts;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.UI.Components
{
    public class CategoryViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryService;

        public CategoryViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IViewComponentResult Invoke()
        {
            var categories = _categoryService.GetAll();
            return View(categories);
        }
    }
}

ECommerce.UI/Components/FeatureItemsViewComponent.cs
using ECommerce.Infrastructure.Services.Abstracts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce.UI.Components
{
    public class FeatureItemsViewComponent: ViewComponent
    {
        private readonly IProductService _productService;

        public FeatureItemsViewComponent(IProductService productService)
        {
            _productService = productService;
        }

        public IViewComponentResult Invoke()
        {
            var products = _productService.GetAll();
            var latestProducts = products.OrderByDescending(x => x.CreatedTime).Take(6).ToList();
            return View(latestProducts);
        }
    }
}

ECommerce.UI/Components/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.UI.Components
{
    public class HeaderViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

ECommerce.UI/Components/MenuViewComponent.cs
using ECommerce.Infrastructure.Services.Abstracts;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.UI.Components
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly IMenuService _menuService;

        public MenuViewComponent(IMenuService menuService)
        {
            _menuService = menuService;
        }

        public IViewComponentResult Invoke()
        {
            var menu = _menuService.GetAll();
            return View(menu);
        }
    }
}

ECommerce.UI/Components/RecommendedViewComponent.cs
using ECommerce.Infrastructure.Services.Abstracts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce.UI.Components
{
    public class RecommendedViewComponent : ViewComponent
    {
        private readonly IProductService _productService;

        public RecommendedViewComponent(IProductService productService)
        {
            _productService = productService;
        }

        public IViewComponentResult Invoke()
        {
            var products = _productService.GetAll();
            var recommended = products.Where(p => p.IsRecommended).Take(10).ToList();
            return View(recommended);
        }
    }
}

ECommerce.UI/Controllers/ProductController.cs
using ECommerce.Infrastructure.Extensions;
using ECommerce.Infrastructure.Services.Abstracts;
using ECommerce.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ECommerce.UI.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index(int categoryId, int brandId, int pageIndex)
        {
            ProductViewModel model = new ProductViewModel();
            model.PageIndex -= 1;

            var products = _productService.GetAll();

            if (categoryId != 0)
                products = products.Where(x => x.CategoryId == categoryId).ToList();

            if (brandId != 0)
                products = products.Where(x => x.BrandId == brandId).ToList();

            model.TotalPageCount = (int)Math.Ceiling((decimal)products.Count / model.Count);
            model.Products = products.Skip(model.PageIndex * model.Count).Take(model.Count).ToList();
            model.CategoryId = categoryId;
            model.BrandId = brandId;

            return View(model);
        }

        public IActionResult ProductDetail(int productId)
        {
            var products = _productService.GetAll();
            var product = products.FirstOrDefault(x => x.ID == productId);

            return View(product);
        }

        public void AddToBasket(int productId, int quantity)
        {
            var basketModel = new BasketModel { Product = _productService.Get(productId), Quantity = quantity };
            var basketList = SessionExtensions.GetObjectFromJson<List<BasketModel>>(HttpContext.Session, "Cart");

            if (basketList == null)
            {
                var cart = new List<BasketModel>();
                cart.Add(basketModel);
                SessionExtensions.SetObjectAsJson(HttpContext.Session, "Cart", cart);
            }
            else
            {
                var index = isExist(productId);
                if (index != -1)
                    basketList[index].Quantity += quantity;
                else
                    basketList.Add(basketModel);

                SessionExtensions.SetObjectAsJson(HttpContext.Session, "Cart", basketList);
            }
        }

        public IActionResult Basket()
        {
            var basketList = SessionExtensions.GetObjectFromJson<List<BasketModel>>(HttpContext.Session, "Cart");

            if (basketList == null)
                basketList = new List<BasketModel>();

            return View(basketList);
        }

        public int UpdateQuantity(int productId, int quantity)
        {
            var basketList = SessionExtensions.GetObjectFromJson<List<BasketModel>>(HttpContext.Session, "Cart");
            var index = isExist(productId);

            if (index != -1)
            {
                basketList[index].Quantity += quantity;

                SessionExtensions.SetObjectAsJson(HttpContext.Session, "Cart", basketList);
                
                return basketList[index].Quantity;
            }
            return 0;
        }

        public void Remove(int productID)
        {
            var basketList = SessionExtensions.GetObjectFromJson<List<BasketModel>>(HttpContext.Session, "Cart");
            var index = isExist(productID);

            basketList.RemoveAt(index);
            SessionExtensions.Set(HttpContext.Session, "Cart", basketList);
        }

        private int isExist(int productId)
        {
            var cart = SessionExtensions.GetObjectFromJson<List<BasketModel>>(HttpContext.Session, "Cart");

            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.ID.Equals(productId))
                    return i;
            }
            return -1;
        }
    }
}

ECommerce.UI/Views/Shared/Components/Header/Default.cshtml
<header id="header">
    <!--header-->
    <div class="header_top">
        <!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle">
        <!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        <a href="index.html"><img src="~/images/home/logo.png" alt="" /></a>
                    </div>
                    <div class="btn-group pull-right">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                USA
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canada</a></li>
                                <li><a href="#">UK</a></li>
                            </ul>
                        </div>

                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                DOLLAR
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canadian Dollar</a></li>
                                <li><a href="#">Pound</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="shop-menu pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-user"></i> Account</a></li>
                            <li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>
                            <li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>
                            <li><i class="fa fa-shopping-cart"></i>@Html.ActionLink("Cart", "Basket", "Product")</li>
                            <li><a href="login.html"><i class="fa fa-lock"></i> Login</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom">
        <!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        @await Component.InvokeAsync("Menu")
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="Search" />
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->