ECommerce.UI/Models/ProductViewModel.cs
using ECommerce.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce.UI.Models
{
    public class ProductViewModel
    {
        //pagination
        public int Count { get; set; } = 6;
        public int PageIndex { get; set; }
        public int TotalPageCount { get; set; }
        public List<Product> Products { get; set; }

        //Filters
        public int BrandId { get; set; }
        public int CategoryId { get; set; }
    }
}

ECommerce.UI/Components/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.UI.Components
{
    public class HeaderViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

ECommerce.UI/Controllers/ProductController.cs
using ECommerce.Infrastructure.Extensions;
using ECommerce.Infrastructure.Services.Abstracts;
using ECommerce.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ECommerce.UI.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index(int categoryId, int brandId, int pageIndex)
        {
            ProductViewModel model = new ProductViewModel();
            model.PageIndex -= 1;

            var products = _productService.GetAll();

            if (categoryId != 0)
                products = products.Where(x => x.CategoryId == categoryId).ToList();

            if (brandId != 0)
                products = products.Where(x => x.BrandId == brandId).ToList();

            model.TotalPageCount = (int)Math.Ceiling((decimal)products.Count / model.Count);
            model.Products = products.Skip(model.PageIndex * model.Count).Take(model.Count).ToList();
            model.CategoryId = categoryId;
            model.BrandId = brandId;

            return View(model);
        }

        public IActionResult ProductDetail(int productId)
        {
            var products = _productService.GetAll();
            var product = products.FirstOrDefault(x => x.ID == productId);

            return View(product);
        }

        public void AddToBasket(int productId, int quantity)
        {
            var basketModel = new BasketModel { Product = _productService.Get(productId), Quantity = quantity };
            var basketList = SessionExtensions.GetObjectFromJson<List<BasketModel>>(HttpContext.Session, "Cart");

            if (basketList == null)
            {
                var cart = new List<BasketModel>();
                cart.Add(basketModel);
                SessionExtensions.SetObjectAsJson(HttpContext.Session, "Cart", cart);
            }
            else
            {
                var index = isExist(productId);
                if (index != -1)
                    basketList[index].Quantity += quantity;
                else
                    basketList.Add(basketModel);

                SessionExtensions.SetObjectAsJson(HttpContext.Session, "Cart", basketList);
            }
        }

        public IActionResult Basket()
        {
            var basketList = SessionExtensions.GetObjectFromJson<List<BasketModel>>(HttpContext.Session, "Cart");

            if (basketList == null)
                basketList = new List<BasketModel>();

            return View(basketList);
        }

        public int UpdateQuantity(int productId, int quantity)
        {
            var basketList = SessionExtensions.GetObjectFromJson<List<BasketModel>>(HttpContext.Session, "Cart");
            var index = isExist(productId);

            if (index != -1)
            {
                basketList[index].Quantity += quantity;

                SessionExtensions.SetObjectAsJson(HttpContext.Session, "Cart", basketList);
                
                return basketList[index].Quantity;
            }
            return 0;
        }

        public void Remove(int productID)
        {
            var basketList = SessionExtensions.GetObjectFromJson<List<BasketModel>>(HttpContext.Session, "Cart");
            var index = isExist(productID);

            basketList.RemoveAt(index);
            SessionExtensions.Set(HttpContext.Session, "Cart", basketList);
        }

        private int isExist(int productId)
        {
            var cart = SessionExtensions.GetObjectFromJson<List<BasketModel>>(HttpContext.Session, "Cart");

            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.ID.Equals(productId))
                    return i;
            }
            return -1;
        }
    }
}

ECommerce.UI/Views/Product/Basket.cshtml
@using ECommerce.UI.Models
@model List<BasketModel>

@{ 
    Layout = null;
}

<html>
<head>
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/css/prettyPhoto.css" rel="stylesheet">
    <link href="~/css/price-range.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/main.css" rel="stylesheet">
    <link href="~/css/responsive.css" rel="stylesheet">

</head>

<body>
    @await Component.InvokeAsync("Header");

    <section id="cart_items">
        <div class="container">
            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="#">Home</a></li>
                    <li class="active">Shopping Cart</li>
                </ol>
            </div>
            <div class="table-responsive cart_info">
                <table class="table table-condensed">
                    <thead>
                        <tr class="cart_menu">
                            <td class="image">Item</td>
                            <td class="description"></td>
                            <td class="price">Price</td>
                            <td class="quantity">Quantity</td>
                            <td class="total">Total</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var basketProduct in Model)
                        {
            <tr>
                <td class="cart_product">
                    <a href=""><img src="images/cart/one.png" alt=""></a>
                </td>
                <td class="cart_description">
                    <h4><a href="">@basketProduct.Product.Name</a></h4>
                    <p>Web ID: @basketProduct.Product.ID</p>
                </td>
                <td class="cart_price">
                    <p>@basketProduct.Product.Price</p>
                </td>
                <td class="cart_quantity">
                    <div class="cart_quantity_button">
                        <a class="cart_quantity_up" href="#" onclick="updateBasket('@basketProduct.Product.ID', 'increase')"> + </a>
                        <input class="cart_quantity_input" type="text" name="quantity" value="@basketProduct.Quantity" autocomplete="off" size="2">
                        <a class="cart_quantity_down" href="#" onclick="updateBasket('@basketProduct.Product.ID', 'descrease')"> - </a>
                    </div>
                </td>
                <td class="cart_total">
                    <p class="cart_total_price">@(basketProduct.Product.Price*basketProduct.Quantity)</p>
                </td>
                <td class="cart_delete">
                    <a class="cart_quantity_delete" href="#" onclick="removeBasket('@basketProduct.Product.ID')"><i class="fa fa-times"></i></a>
                </td>
            </tr>}
                    </tbody>
                </table>
            </div>
        </div>
    </section> <!--/#cart_items-->

    <script src="~/js/jquery.js"></script>
    <script type="text/javascript">
        function updateBasket(productId, type) {
            debugger
            var quantity = 0;
            if (type == "increase") {
                quantity++;
            }
            else {
                quantity--;
            }

            $.ajax({
                type: 'POST',
                url: '/Product/UpdateQuantity',
                data: { "productId": productId, "quantity": quantity },
                success: function (data) {
                    location.reload();
                },
                error: function (err) {
                    alert(err);
                }
            });
        }

        function removeBasket(productId) {
            var status = false;

            $.ajax(
                {
                    type: 'POST',
                    url: "/Product/Remove",
                    data: { "ProductId": productId },
                    success: function (data) {
                        location.reload();
                    },
                    error: function (err) { alert(err); }
                })
        }
    </script>
</body>

</html>

ECommerce.UI/Views/Product/Index.cshtml
@using ECommerce.UI.Models
@model ProductViewModel

<div class="features_items">
    @foreach (var product in Model.Products)
    {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        <img src="~/images/home/product6.jpg" alt="" />
                        <h2>@product.Price</h2>
                        <p>@product.Name</p>
                        <a href="'@Url.Action("ProductDetail", "Product",new { productId=product.ID})'" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </div>
                    <div class="product-overlay">
                        <div class="overlay-content">
                            <h2>@product.Price</h2>
                            <p>@product.Name</p>
                            <a href="'@Url.Action("ProductDetail", "Product", new { productId = product.ID})'" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                        </div>
                    </div>
                </div>
                <div class="choose">
                    <ul class="nav nav-pills nav-justified">
                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                    </ul>
                </div>
            </div>
        </div>
    }

    <ul class="pagination">
        @for (int i = 1; i <= Model.TotalPageCount; i++)
        {
            <li @(i == Model.PageIndex +1 ? "class='active'" : "")><a href="@Url.Action("Index", "Product", new { categoryId=Model.CategoryId, brandID=Model.BrandId, pageIndex=i})">@i</a></li>
        }
    </ul>

</div><!--features_items-->

ECommerce.UI/Views/Product/ProductDetail.cshtml
@using ECommerce.Entities
@model Product

    <div class="product-details">
        <!--product-details-->
        <div class="col-sm-5">
            <div class="view-product">
                <img src="~/images/product-details/1.jpg" alt="@Model.Name" />
                <h3>ZOOM</h3>
            </div>
            <div id="similar-product" class="carousel slide" data-ride="carousel">

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="item active">
                        <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                        <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                        <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                    </div>
                    <div class="item">
                        <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                        <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                        <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                    </div>
                    <div class="item">
                        <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                        <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                        <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                    </div>
                </div>

                <!-- Controls -->
                <a class="left item-control" href="#similar-product" data-slide="prev">
                    <i class="fa fa-angle-left"></i>
                </a>
                <a class="right item-control" href="#similar-product" data-slide="next">
                    <i class="fa fa-angle-right"></i>
                </a>
            </div>
        </div>
        <div class="col-sm-7">
            <div class="product-information">
                <!--/product-information-->
                <img src="images/product-details/new.jpg" class="newarrival" alt="" />
                <h2>@Model.Name</h2>
                <p>Web ID: @Model.ID</p>
                <img src="images/product-details/rating.png" alt="" />
                <span>
                    <span>@Model.Price</span>
                    <label>Quantity:</label>
                    <input id="quantity" type="text" value="1"/>
                    <button type="button" class="btn btn-fefault cart" onclick="addToBasket('@Model.ID')">
                        <i class="fa fa-shopping-cart"></i>
                        Add to cart
                    </button>
                </span>
                <p><b>Availability:</b> In Stock</p>
                <p><b>Condition:</b> @Model.IsNewProduct ? "New" : "Regular"</p>
                <p><b>Brand:</b> @Model.Brand.Name</p>
                <a href=""><img src="images/product-details/share.png" class="share img-responsive" alt="" /></a>
            </div><!--/product-information-->
        </div>
    </div><!--/product-details-->

    <div class="category-tab shop-details-tab">
        <!--category-tab-->
        <div class="col-sm-12">
            <ul class="nav nav-tabs">
                <li><a href="#details" data-toggle="tab">Details</a></li>
                <li><a href="#companyprofile" data-toggle="tab">Company Profile</a></li>
                <li><a href="#tag" data-toggle="tab">Tag</a></li>
                <li class="active"><a href="#reviews" data-toggle="tab">Reviews (5)</a></li>
            </ul>
        </div>
        <div class="tab-content">
            <div class="tab-pane fade" id="details">
                @foreach (var item in Model.Pictures)
                {
                    <div class="col-sm-3">
                        <div class="product-image-wrapper">
                            <div class="single-products">
                                <div class="productinfo text-center">
                                    <img src="@item.Path" alt="" />
                                    <h2>@Model.Price</h2>
                                    <p>@Model.Name</p>
                                    <button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>

        </div>
    </div><!--/category-tab--> 

    <script>
        function addToBasket(productId) {
            var quantity = $("#quantity").val();

            $.ajax({
                type: 'POST',
                url: '/Product/AddToBasket',
                data: { "productId": productId, "quantity": quantity },
                success: function (data) { alert("ok"); },
                error: function (err) { alert(err); }
            });
        }
    </script>